### ISSUE TITLE
_getNodeTree fails if node stage was called without argument

### ISSUE THREAD

**Issue by jangalda-nsc** [gdemengin/pipeline-logparser#11]
Hi @gdemengin ,
At the beginning I would like thank you for sharing this great library with the world.

I want to put it as component of library I develop. Works great in most cases, but getting pipeline log failed when script tries to get label info from agent, which have no label specified.
The easiest pipeline to reproduce this issue is:
```
node {
  echo "any node"
}
```
Because 'node' is called without argument, script fails on:
```
assert argAction.size() == 1
```

I workaround this issue by recording always hostname  (it's even more useful information for me - in the future I plan to add method for listing all agents used in pipelines)

Workaround here:
```
//                def argAction = node.actions.findAll { it.class == org.jenkinsci.plugins.workflow.cps.actions.ArgumentsActionImpl }
//                assert argAction.size() == 1
//                if (argAction[0].unmodifiedArguments) {
//                    label=argAction[0].argumentsInternal.label
//                }
//                else {
                    // the label was filtered: record the hostname then
                    def wsAction = node.actions.findAll { it.class == org.jenkinsci.plugins.workflow.support.actions.WorkspaceActionImpl }
                    assert wsAction.size() == 1
                    label=wsAction[0].node
//                }
```
It's just fast and stupid workaround and I believe it would be better to fix it upstream.
What are your plan for this library? Do you have to fix bugs and develop it?

Thanks,
Jan

**Comment by gdemengin** [comment]
thanks, did not think of that one

https://github.com/gdemengin/pipeline-logparser/pull/12 fixes it by allowing missing labels

and I put a new field "host" to record hostnames all the time.

> What are your plan for this library? Do you have to fix bugs and develop it?

not much plans other than fixing bugs and improving tests

**Comment by jangalda-nsc** [comment]
Thanks for fast response, everything works.

Btw. what is performance of `getLogsWithBranchInfo` method in your environment? In my plan, which has 10 parallel stages, it can take 90s to execute this method. Logs with simpler plans are usually parsed within 10-15 seconds

**Comment by gdemengin** [comment]
yes with 50 to 100 branches it usually takes 1 to 2 minutes (that's 1 to 2 minutes where other branches sit and wait so it makes it a good idea to not call that function too often from branches)

In extreme cases (millions of operations) it can be much longer, and RAM seems to be the first bottleneck: good tuning on the server side might certainly help.

on the client side, I tried to cache as much as possible to avoid losing time re-parsing steps already over. 
I don't really have any idea to make it faster.
