### ISSUE TITLE
Branch information without stage or parallel

### ISSUE THREAD

**Issue by stephanvalentan** [gdemengin/pipeline-logparser#22]
Hello,
thanks for your work, this plugin really helps with organizing our logs!
I just have one question, is it possible to inject some branch information without having to use a `stage` or a `parallel` block?

My use-case is that I'm running a series of validation tools against our product, for which I both want console logs in Jenkins, but also obtain a logfile that i can process further.
Using `parallel` blocks works fine for this, but it kinda messes up the classic pipeline stage view, as well as the BlueOcean view for the builds- seems like it does not work very well with nested parallel blocks (or stages, for that matter).

Do you have any suggestion of how to deal with this?

**Comment by gdemengin** [comment]
Sorry I don't know of any other way than `parallel` or `stage` to 'isolate' a block and its logs

I often use `parallel` with only one branch to get logs for a particular section of code (and I avoid looking at blue ocean when such blocks are nested)
or I redirect logs in a file for `sh` steps

what you need is a new `withLogs { ... )` function with ways to access the logs as a file or as a link (If something like that existed the rest of the logparser library could become less usefull)

**Comment by stephanvalentan** [comment]
I actually spent a couple of hours digging through API docs for the jenkins stage-view plugin and figured out a way to access the logs via the REST API in a way that might just work for me.
If you know your own node-id, its possible to get the id of the containing stage, and from there it's possible to access a list of all steps of the stage in question.
In our case I just want to be able to access the logs for a `sh` step just before me to in another `sh` steps that does some post-processing on the logs, this mean I just use the second-to-last element of the node-list and fetch the output.

    GET https://example.com/jenkins/job/<job-name>/<run-id>/wfapi/describe
    {
        ...
        "stages": [ {"id" : "1", "name": "build", ...}, ...]
        ...
    }
    
    GET https://example.com/jenkins/job/<job-name>/<run-id>/execution/node/<stage-id>/wfapi/describe
    {
        ...
        "stageFlowNodes": [ {"id": "2", ...} ...]
        ...
    }
    
    GET https://example.com/jenkins/job/<job-name>/<run-id>/execution/node/<step-id>/wfapi/log
    profit

I don't have any experience with custom pipeline steps, and whether it would be possible to automatically obtain the node-ids of contained steps through the `withLogs {}` block as you suggested, this would probably reduce the overhead of collecting the logs significantly!

**Comment by gdemengin** [comment]
interesting, I did not know this API
indeed getting the node ids of all the steps is the key. maybe it can be done

meanwhile here is another way to get the last node id and the associated log url (as long as there is no other step running in parallel)

```
@Library('pipeline-logparser@3.2') _

def log_url
node {
    sh('echo 1')
    log_url=logparser.getPipelineStepsUrls().last().log.replaceAll(/log$/, 'wfapi/log')
}
print log_url
```
result
```
[Pipeline] echo
http://ci.jenkins.internal:8080/job/sample-pipeline/16/execution/node/5/wfapi/log
```

**Comment by stephanvalentan** [comment]
Sorry i forgot to post the link to the API: https://github.com/jenkinsci/pipeline-stage-view-plugin/blob/master/rest-api/README.md

Thanks for your insights in any way!
