### ISSUE TITLE
Usability of this library in other projects

### ISSUE THREAD

**Issue by garethhurley** [gdemengin/pipeline-logparser#3]
Hi
Well done on a very useful and well-documented library that closes a real gap in Jenkins Pipeline functionality.
Would it be possible to add an Open Source license to your repository?

The reason is:
- To make it easier to use the library as part of other projects 
- For use in commercial and non-commercial projects
- While protecting your ownership of the code and acknowledgement of you as the author

Github suggests the MIT license (and I would agree with this)
It is simple, easy-to-understand, widely used and gives a high level of 'freedom' to use your library.

I'm happy to answer any questions and/or to make a pull request to add the license.

Gareth

**Comment by gdemengin** [comment]
thank you
just added the license file
